# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b0d0f07149fdcc603ed652a7b4c0baf6"
application_url = "https://rare-grab-survive-exclusive.trycloudflare.com"
embedded = true
name = "Product Badge App"
handle = "product-label-app-1"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://rare-grab-survive-exclusive.trycloudflare.com/auth/callback",
  "https://rare-grab-survive-exclusive.trycloudflare.com/auth/shopify/callback",
  "https://rare-grab-survive-exclusive.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
